package:
  name: roq-udp-subscriber
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: True  # [win]
  number: {{ ROQ_BUILD_NUMBER if ROQ_BUILD_NUMBER is defined else GIT_DESCRIBE_NUMBER }}                                
  script_env:                                                                                                           
    - ROQ_BUILD_NUMBER                                                                                                  
    - ROQ_BUILD_TYPE
  run_exports:
    - {{ pin_subpackage('roq-udp-subscriber', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
  host:
    - roq-core
    - abseil-cpp
    - roq-oss-benchmark
    - roq-oss-brotli
    - roq-oss-catch2
    - roq-oss-libsodium
    - roq-oss-magic_enum
    - roq-oss-tomlplusplus
    - roq-oss-range-v3
    - roq-oss-re2
    - roq-server

about:
  home: https://roq-trading.com
  doc_url: https://roq-trading.com/docs
  dev_url: https://github.com/roq-trading
  license: Commercial
  license_family: PROPRIETARY
  license_file: LICENSE
  summary: Roq UDP Subscriber
